version: 0.2


phases:
  install:
    runtime-version:
      nodejs: 18
    commands:
      - echo "Installing dependencies..."
      - npm install
  build:
    commands:
      - echo "Building Next.js application..."
      - npm run build
      - cp appspec.yml ./out/appspec.yml
      - cp -r codedeploy-scripts/* out/scripts/
  post_build:
    commands:
      - echo "Build completed on `date`"
artifacts:
  files:
    - '**/*'
  base-directory: out
